FactoryBot.create(:user,:with_movie_purchases,:with_season_purchases, movie_count:2, season_count:1)
FactoryBot.create(:user,:with_movie_purchases,:with_season_purchases, movie_count:1, season_count:1)
FactoryBot.create(:movie,:with_purchase_options, purchase_option_count:2)
FactoryBot.create(:movie,:with_purchase_options, purchase_option_count:2)
FactoryBot.create(:season,:with_episodes,:with_purchase_options,episodes_count:3, purchase_option_count:2)
FactoryBot.create(:season,:with_episodes,:with_purchase_options,episodes_count:2, purchase_option_count:1)
FactoryBot.create(:movie,:with_purchase_options, purchase_option_count:2)
